FROM ubuntu:latest

RUN apt install software-properties-common && \
   apt-get install apt-add-repository -y && \
   #  && \
   add-apt-repository ppa:ecal/ecal-latest && \
   apt update && \
   apt install ecal
